#!/bin/sh
set -eu

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT_DIR"

cd "$ROOT_DIR/backend"
docker compose up -d --build

cd "$ROOT_DIR/frontend"
docker compose up -d --build

cd "$ROOT_DIR/infra/streaming"
docker compose up -d --force-recreate

cd "$ROOT_DIR/infra/audio"
docker compose up -d --force-recreate