#!/bin/sh
set -eu

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT_DIR"

cd "$ROOT_DIR/frontend"
docker compose down

cd "$ROOT_DIR/infra/audio"
docker compose down

cd "$ROOT_DIR/infra/streaming"
docker compose down

cd "$ROOT_DIR/backend"
docker compose down

echo ""
echo "  Todos los servicios detenidos."
echo ""
